"""empty message

Revision ID: 5ab657203bfe
Revises: 7431c72b8461
Create Date: 2018-11-17 16:50:07.639541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab657203bfe'
down_revision = '7431c72b8461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('summary', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'summary')
    # ### end Alembic commands ###
