"""empty message

Revision ID: a5d7266ce6f0
Revises: 4fc64a50f489
Create Date: 2018-10-18 14:29:22.427884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d7266ce6f0'
down_revision = '4fc64a50f489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('image', sa.String(length=50), nullable=False))
    op.drop_column('blogposts', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('picture', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('blogposts', 'image')
    # ### end Alembic commands ###
